### ISSUE TITLE
Train-Departure-Data missing from app (endless loading screen)

### ISSUE THREAD

**Issue by csmnn** [dbbahnhoflive/dbbahnhoflive-android#2]
I guess, the issues should be written in english, correct? It would be great, if you could provide a template. ;)

Running / Using the android-app in an emulator will not load the departure data for trains. Is this the intended behavior for the community-edition?

* For all tested train stations, the train-departure-data is not loaded
    * It just shows an endless loading circle
    * (Tested: Berlin Hbf, FFM Hbf)
    * in multiple Internet-Networks (Wifi + Mobile)
* I'd expect either the same info as for local busses (ÖPNV): "No data available" or the correct information.
    * Is this the intended behavior?

Log:
```2020-07-15 14:32:42.654 8273-8273/de.deutschebahn.bahnhoflive.community.debug W/ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@95fcd9
2020-07-15 14:32:42.683 8273-8273/de.deutschebahn.bahnhoflive.community.debug I/IssueTracker: Catched
    com.android.volley.VolleyError: Missing implementation
        at de.deutschebahn.bahnhoflive.repository.VolleyRestListenerXKt.fail(VolleyRestListenerX.kt:8)
        at de.deutschebahn.bahnhoflive.repository.map.MapRepository.queryPois(MapRepository.kt:30)
        at de.deutschebahn.bahnhoflive.repository.RimapPOIListResource.onStartLoading(RimapPOIListResource.java:18)
        at de.deutschebahn.bahnhoflive.repository.RemoteResource.startLoading(RemoteResource.java:27)
        at de.deutschebahn.bahnhoflive.repository.RemoteResource.loadData(RemoteResource.java:17)
        at de.deutschebahn.bahnhoflive.repository.RimapPOIListResource.load(RimapPOIListResource.java:26)
        at de.deutschebahn.bahnhoflive.repository.ShopsResource.initialize(ShopsResource.java:46)
        at de.deutschebahn.bahnhoflive.ui.station.StationViewModel.initialize(StationViewModel.kt:261)
        at de.deutschebahn.bahnhoflive.ui.station.StationActivity.onCreate(StationActivity.java:122)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
2020-07-15 14:32:42.685 8273-8273/de.deutschebahn.bahnhoflive.community.debug I/IssueTracker: Catched
    com.android.volley.VolleyError: Missing implementation
        at de.deutschebahn.bahnhoflive.repository.VolleyRestListenerXKt.fail(VolleyRestListenerX.kt:8)
        at de.deutschebahn.bahnhoflive.repository.localtransport.LocalTransportRepository.queryNearbyStations(LocalTransportRepository.kt:22)
        at de.deutschebahn.bahnhoflive.repository.HafasStationsResource.onStartLoading(HafasStationsResource.kt:33)
        at de.deutschebahn.bahnhoflive.repository.RemoteResource.startLoading(RemoteResource.java:27)
        at de.deutschebahn.bahnhoflive.repository.RemoteResource.loadData(RemoteResource.java:17)
        at de.deutschebahn.bahnhoflive.repository.RemoteResource.loadIfNecessary(RemoteResource.java:62)
        at de.deutschebahn.bahnhoflive.ui.station.localtransport.LocalTransportViewModel$initialize$1.onChanged(LocalTransportViewModel.kt:53)
        at de.deutschebahn.bahnhoflive.ui.station.localtransport.LocalTransportViewModel$initialize$1.onChanged(LocalTransportViewModel.kt:44)
        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:131)
        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:144)
        at androidx.lifecycle.LiveData$ObserverWrapper.activeStateChanged(LiveData.java:443)
        at androidx.lifecycle.LiveData.observeForever(LiveData.java:232)
        at de.deutschebahn.bahnhoflive.util.ManagedObserver.<init>(ManagedObserver.java:11)
        at de.deutschebahn.bahnhoflive.ui.station.localtransport.LocalTransportViewModel$initialize$1.<init>(LocalTransportViewModel.kt:44)
        at de.deutschebahn.bahnhoflive.ui.station.localtransport.LocalTransportViewModel.initialize(LocalTransportViewModel.kt:44)
        at de.deutschebahn.bahnhoflive.ui.station.StationViewModel.initialize(StationViewModel.kt:268)
        at de.deutschebahn.bahnhoflive.ui.station.StationActivity.onCreate(StationActivity.java:122)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
2020-07-15 14:32:42.686 8273-8273/de.deutschebahn.bahnhoflive.community.debug I/IssueTracker: Catched
    com.android.volley.VolleyError: Missing implementation
        at de.deutschebahn.bahnhoflive.repository.VolleyRestListenerXKt.fail(VolleyRestListenerX.kt:8)
        at de.deutschebahn.bahnhoflive.repository.map.MapRepository.queryStationInfo(MapRepository.kt:23)
        at de.deutschebahn.bahnhoflive.repository.RimapStationFeatureCollectionResource.onStartLoading(RimapStationFeatureCollectionResource.java:11)
        at de.deutschebahn.bahnhoflive.repository.RemoteResource.startLoading(RemoteResource.java:27)
        at de.deutschebahn.bahnhoflive.repository.RemoteResource.loadData(RemoteResource.java:17)
        at de.deutschebahn.bahnhoflive.repository.RimapStationFeatureCollectionResource.loadData(RimapStationFeatureCollectionResource.java:28)
        at de.deutschebahn.bahnhoflive.repository.RemoteResource.loadIfNecessary(RemoteResource.java:62)
        at de.deutschebahn.bahnhoflive.ui.station.StationViewModel.initialize(StationViewModel.kt:271)
        at de.deutschebahn.bahnhoflive.ui.station.StationActivity.onCreate(StationActivity.java:122)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
2020-07-15 14:32:42.734 8273-8273/de.deutschebahn.bahnhoflive.community.debug I/IssueTracker: Catched
    com.android.volley.VolleyError: Missing implementation
        at de.deutschebahn.bahnhoflive.repository.VolleyRestListenerXKt.fail(VolleyRestListenerX.kt:8)
        at de.deutschebahn.bahnhoflive.repository.localtransport.LocalTransportRepository.queryNearbyStations(LocalTransportRepository.kt:22)
        at de.deutschebahn.bahnhoflive.repository.HafasStationResource.onStartLoading(HafasStationResource.java:45)
        at de.deutschebahn.bahnhoflive.repository.RemoteResource.startLoading(RemoteResource.java:27)
        at de.deutschebahn.bahnhoflive.repository.RemoteResource.loadData(RemoteResource.java:17)
        at de.deutschebahn.bahnhoflive.repository.HafasStationResource.initialize(HafasStationResource.java:27)
        at de.deutschebahn.bahnhoflive.ui.timetable.localtransport.HafasTimetableViewModel$4.onChanged(HafasTimetableViewModel.java:105)
        at de.deutschebahn.bahnhoflive.ui.timetable.localtransport.HafasTimetableViewModel$4.onChanged(HafasTimetableViewModel.java:102)
        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:131)
        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:144)
        at androidx.lifecycle.LiveData$ObserverWrapper.activeStateChanged(LiveData.java:443)
        at androidx.lifecycle.LiveData.observeForever(LiveData.java:232)
        at de.deutschebahn.bahnhoflive.util.ManagedObserver.<init>(ManagedObserver.java:11)
        at de.deutschebahn.bahnhoflive.ui.timetable.localtransport.HafasTimetableViewModel$4.<init>(HafasTimetableViewModel.java:102)
        at de.deutschebahn.bahnhoflive.ui.timetable.localtransport.HafasTimetableViewModel.initialize(HafasTimetableViewModel.java:102)
        at de.deutschebahn.bahnhoflive.ui.station.StationActivity.onCreate(StationActivity.java:203)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
2020-07-15 14:32:42.863 8273-8273/de.deutschebahn.bahnhoflive.community.debug I/TrackingManager: ADBMobile.trackState: h1:1866:frankfurt(main)hbf, {Page3=frankfurt(main)hbf, Page1=h1, Page2=1866, ID=1866, Name=Frankfurt(Main)Hbf}
2020-07-15 14:32:42.865 8273-8273/de.deutschebahn.bahnhoflive.community.debug I/IssueTracker: Catched
    com.android.volley.VolleyError: Missing implementation
        at de.deutschebahn.bahnhoflive.repository.VolleyRestListenerXKt.fail(VolleyRestListenerX.kt:8)
        at de.deutschebahn.bahnhoflive.repository.misc.EinkaufsbahnhofRepository.queryStation(EinkaufsbahnhofRepository.kt:18)
        at de.deutschebahn.bahnhoflive.repository.EinkaufsbahnhofStationResponseResource.onStartLoading(EinkaufsbahnhofStationResponseResource.java:14)
        at de.deutschebahn.bahnhoflive.repository.RemoteResource.startLoading(RemoteResource.java:27)
        at de.deutschebahn.bahnhoflive.repository.RemoteResource.loadData(RemoteResource.java:17)
        at de.deutschebahn.bahnhoflive.repository.RemoteResource.onRefresh(RemoteResource.java:58)
        at de.deutschebahn.bahnhoflive.repository.Resource.refresh(Resource.java:37)
        at de.deutschebahn.bahnhoflive.repository.ShopsResource$4.onChanged(ShopsResource.java:77)
        at de.deutschebahn.bahnhoflive.repository.ShopsResource$4.onChanged(ShopsResource.java:73)
        at androidx.lifecycle.MediatorLiveData$Source.onChanged(MediatorLiveData.java:152)
        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:131)
        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:144)
        at androidx.lifecycle.LiveData$ObserverWrapper.activeStateChanged(LiveData.java:443)
        at androidx.lifecycle.LiveData.observeForever(LiveData.java:232)
        at androidx.lifecycle.MediatorLiveData$Source.plug(MediatorLiveData.java:141)
        at androidx.lifecycle.MediatorLiveData.onActive(MediatorLiveData.java:118)
        at androidx.lifecycle.LiveData$ObserverWrapper.activeStateChanged(LiveData.java:437)
        at androidx.lifecycle.LiveData$LifecycleBoundObserver.onStateChanged(LiveData.java:395)
        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:361)
        at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:300)
        at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:339)
        at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:145)
        at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:131)
        at androidx.fragment.app.Fragment.performStart(Fragment.java:2735)
        at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:365)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1194)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1497)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
        at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2169)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1992)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1947)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1849)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2629)
        at androidx.fragment.app.FragmentManager.dispatchStart(FragmentManager.java:2583)
        at androidx.fragment.app.Fragment.performStart(Fragment.java:2739)
        at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:365)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1194)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1497)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2625)
        at androidx.fragment.app.FragmentManager.dispatchStart(FragmentManager.java:2583)
        at androidx.fragment.app.FragmentController.dispatchStart(FragmentController.java:258)
2020-07-15 14:32:42.866 8273-8273/de.deutschebahn.bahnhoflive.community.debug I/IssueTracker:     at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:550)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:201)
        at de.deutschebahn.bahnhoflive.ui.station.StationActivity.onStart(StationActivity.java:225)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1425)
        at android.app.Activity.performStart(Activity.java:7825)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3294)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
2020-07-15 14:32:42.882 8273-8273/de.deutschebahn.bahnhoflive.community.debug W/community.debu: Accessing hidden field Landroid/view/View;->mAccessibilityDelegate:Landroid/view/View$AccessibilityDelegate; (greylist, reflection, allowed)
2020-07-15 14:32:42.937 8273-8273/de.deutschebahn.bahnhoflive.community.debug W/StationViewModel: Missing implementation
    com.android.volley.VolleyError: Missing implementation
        at de.deutschebahn.bahnhoflive.repository.VolleyRestListenerXKt.fail(VolleyRestListenerX.kt:8)
        at de.deutschebahn.bahnhoflive.repository.misc.EinkaufsbahnhofRepository.queryStations(EinkaufsbahnhofRepository.kt:10)
        at de.deutschebahn.bahnhoflive.ui.station.StationViewModel$einkaufsbahnhofListLiveData$1.onActive(StationViewModel.kt:155)
        at androidx.lifecycle.LiveData$ObserverWrapper.activeStateChanged(LiveData.java:437)
        at androidx.lifecycle.LiveData.observeForever(LiveData.java:232)
        at androidx.lifecycle.MediatorLiveData$Source.plug(MediatorLiveData.java:141)
        at androidx.lifecycle.MediatorLiveData.onActive(MediatorLiveData.java:118)
        at androidx.lifecycle.LiveData$ObserverWrapper.activeStateChanged(LiveData.java:437)
        at androidx.lifecycle.LiveData.observeForever(LiveData.java:232)
        at androidx.lifecycle.MediatorLiveData$Source.plug(MediatorLiveData.java:141)
        at androidx.lifecycle.MediatorLiveData.addSource(MediatorLiveData.java:96)
        at androidx.lifecycle.Transformations$2.onChanged(Transformations.java:152)
        at androidx.lifecycle.MediatorLiveData$Source.onChanged(MediatorLiveData.java:152)
        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:131)
        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:144)
        at androidx.lifecycle.LiveData$ObserverWrapper.activeStateChanged(LiveData.java:443)
        at androidx.lifecycle.LiveData.observeForever(LiveData.java:232)
        at androidx.lifecycle.MediatorLiveData$Source.plug(MediatorLiveData.java:141)
        at androidx.lifecycle.MediatorLiveData.onActive(MediatorLiveData.java:118)
        at androidx.lifecycle.LiveData$ObserverWrapper.activeStateChanged(LiveData.java:437)
        at androidx.lifecycle.LiveData.observeForever(LiveData.java:232)
        at androidx.lifecycle.MediatorLiveData$Source.plug(MediatorLiveData.java:141)
        at androidx.lifecycle.MediatorLiveData.onActive(MediatorLiveData.java:118)
        at androidx.lifecycle.LiveData$ObserverWrapper.activeStateChanged(LiveData.java:437)
        at androidx.lifecycle.LiveData$LifecycleBoundObserver.onStateChanged(LiveData.java:395)
        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:361)
        at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:300)
        at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:339)
        at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:145)
        at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:131)
        at androidx.fragment.app.FragmentViewLifecycleOwner.handleLifecycleEvent(FragmentViewLifecycleOwner.java:51)
        at androidx.fragment.app.Fragment.performStart(Fragment.java:2737)
        at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:365)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1194)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1497)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
        at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2169)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1992)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1947)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1849)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2629)
        at androidx.fragment.app.FragmentManager.dispatchStart(FragmentManager.java:2583)
        at androidx.fragment.app.Fragment.performStart(Fragment.java:2739)
        at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:365)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1194)
2020-07-15 14:32:42.937 8273-8273/de.deutschebahn.bahnhoflive.community.debug W/StationViewModel:     at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1497)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2625)
        at androidx.fragment.app.FragmentManager.dispatchStart(FragmentManager.java:2583)
        at androidx.fragment.app.FragmentController.dispatchStart(FragmentController.java:258)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:550)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:201)
        at de.deutschebahn.bahnhoflive.ui.station.StationActivity.onStart(StationActivity.java:225)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1425)
        at android.app.Activity.performStart(Activity.java:7825)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3294)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

Pic:
![image](https://user-images.githubusercontent.com/15031346/87556815-6724c800-c6b7-11ea-85d8-ebf14835fd29.png)

**Comment by mrcodeelements** [comment]
Hi c! ;)

Thanks for your feedback. As we just start to learn about all of this, we don't have any idea of a useful template yet. So, please just provide your feedback the way it feels sensible to you!

It is indeed intended that the community edition lacks several backend services. We plan on providing fallback implementations that do a little bit more than just failing. But we didn't want to wait for it to be done to go open source. You and everybody else is invited to do the job for us and the community! :)

I am going to forward the issue that instead of failing there is an endless progress indication regarding train departures.

Thanks again and it's nice to hear from you! ;)
